apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nfs-provisioner
    name: s2i-core-rhel7
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.access.redhat.com/rhscl/s2i-core-rhel7:latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/rhscl/s2i-core-rhel7:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nfs-provisioner
    name: nfs-provisioner
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nfs-provisioner
    name: nfs-provisioner
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: nfs-provisioner:latest
    postCommit: {}
    resources: {}
    source:
      git:
        ref: master
        uri: https://github.com/apoletics/mynfsprovisioner.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: s2i-core-rhel7:latest
      type: Source
    triggers:
    - github:
        secret: rsoGM1A5jSNN0UgNg4px
      type: GitHub
    - generic:
        secret: wiqRXHR6xQlbA5majy5I
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nfs-provisioner
    name: nfs-provisioner
  spec:
    replicas: 1
    selector:
      app: nfs-provisioner
      deploymentconfig: nfs-provisioner
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: nfs-provisioner
          deploymentconfig: nfs-provisioner
      spec:
        containers:
        - env:
          - name: NFS_BASE_PATH
            value: /nfs
          - name: NFS_HOST
            value: 172.17.0.1
          image: nfs-provisioner:latest
          name: nfs-provisioner
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - nfs-provisioner
        from:
          kind: ImageStreamTag
          name: nfs-provisioner:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
kind: List
metadata: {}
